export const RENTAL_LIST_REQUEST = "RENTAL_LIST_REQUEST";
export const RENTAL_LIST_SUCCESS = "RENTAL_LIST_SUCCESS";   
export const RENTAL_LIST_FAIL = "RENTAL_LIST_FAIL";

export const RENTAL_DETAILS_REQUEST = "RENTAL_DETAILS_REQUEST";
export const RENTAL_DETAILS_SUCCESS = "RENTAL_DETAILS_SUCCESS";
export const RENTAL_DETAILS_FAIL = "RENTAL_DETAILS_FAIL";


