# Generated by Django 5.1.7 on 2025-04-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0002_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='rentalname',
            new_name='productname',
        ),
    ]
