# Generated by Django 5.1.7 on 2025-04-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0003_rename_rentalname_rental_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='productbrand',
            new_name='rentalbrand',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='productcategory',
            new_name='rentalcategory',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='productdescription',
            new_name='rentaldescription',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='productname',
            new_name='rentalname',
        ),
    ]
