# Generated by Django 5.1.7 on 2025-04-25 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0004_rename_productbrand_rental_rentalbrand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rental',
            new_name='Rentals',
        ),
    ]
