# Generated by Django 5.1.7 on 2025-04-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0005_rename_rental_rentals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productcategory',
        ),
    ]
