# Generated by Django 5.1.7 on 2025-04-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0006_remove_products_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productcategory',
            field=models.CharField(blank=True, choices=[('shirts', 'Shirts'), ('jackets', 'Jackets'), ('bags', 'Bags'), ('shoes', 'Shoes'), ('others', 'Others')], default='shirts', max_length=20),
        ),
    ]
