# Generated by Django 5.1.7 on 2025-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0007_products_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='countInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='productcategory',
            field=models.CharField(blank=True, choices=[('Shirts', 'Shirts'), ('Pants', 'Pants'), ('Jackets', 'Jackets'), ('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Womens Wear', 'Womens Wear'), ('Others', 'Others')], default='shirts', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='rentalcategory',
            field=models.CharField(blank=True, choices=[('Shirts', 'Shirts'), ('Pants', 'Pants'), ('Jackets', 'Jackets'), ('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Womens Wear', 'Womens Wear'), ('Others', 'Others')], default='shirts', max_length=20),
        ),
    ]
