# Generated by Django 5.1.7 on 2025-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0008_rentals_countinstock_alter_products_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='rentalcategory',
            field=models.CharField(blank=True, choices=[('costumes', 'Costumes'), ('props', 'props'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Womens Wear', 'Womens Wear'), ('Others', 'Other Rentals')], default='shirts', max_length=20),
        ),
    ]
