# Generated by Django 5.1.7 on 2025-04-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0009_alter_rentals_rentalcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
