# Generated by Django 5.1.7 on 2025-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0011_order_orderitem_rentalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
