# Generated by Django 5.1.7 on 2025-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0012_rentals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
