# Generated by Django 5.1.7 on 2025-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftapp', '0013_alter_rentals_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('feedback', 'General Feedback/Question'), ('sell', 'Selling My Clothes/Items'), ('rental', 'Rental Inquiry'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rentals',
            name='rentalcategory',
            field=models.CharField(blank=True, choices=[('costumes', 'Costumes'), ('props', 'props'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Womens Wear', 'Womens Wear'), ('Others', 'Other Rentals')], default='costumes', max_length=20),
        ),
    ]
